/**
 * Wraparound-cover spine-width calculation. Book Studio's Cover and Back
 * Cover are two independent structural pages today (no single wraparound
 * artwork is generated by this app yet — see `docs/STATUS.md` Phase 45),
 * but authors preparing a print-ready wraparound cover file for KDP or
 * IngramSpark still need to know how wide the spine strip between the two
 * panels must be, and that width depends on the book's final page count
 * and paper stock — information only this app actually has (the live,
 * paginated page count), so surfacing it here removes a manual lookup step
 * per `CLAUDE.md`'s "every feature should reduce the amount of work
 * required from the user."
 *
 * Constants are Amazon KDP's own published pages-per-inch figures for
 * paperback spine width (the same public source already cited by
 * `virtualEditor/checkers/printReadiness.ts`'s `kdpGutterMarginChecker`
 * for its gutter-margin table). IngramSpark publishes very slightly
 * different constants per paper stock; KDP's are used here as the single
 * reference point, with rounding, so this is always an estimate — worded
 * as such wherever it's displayed, never a guarantee.
 */

export type CoverPaperType = 'white' | 'cream' | 'colorStandard' | 'colorPremium'

const PAGES_PER_INCH: Record<CoverPaperType, number> = {
  white: 444,
  cream: 400,
  colorStandard: 444,
  colorPremium: 400,
}

export const PAPER_TYPE_LABELS: Record<CoverPaperType, string> = {
  white: 'White paper (B&W)',
  cream: 'Cream paper (B&W)',
  colorStandard: 'Standard colour paper',
  colorPremium: 'Premium colour paper',
}

/** Minimum page count KDP accepts for a paperback — below this, no spine
 * text should be printed at all (the spine is too thin to hold text
 * legibly), matching Amazon's own published guidance. */
export const MIN_PAGE_COUNT_FOR_SPINE_TEXT = 130

export function computeSpineWidthIn(pageCount: number, paperType: CoverPaperType = 'white'): number {
  if (pageCount <= 0) return 0
  return pageCount / PAGES_PER_INCH[paperType]
}

export function computeSpineWidthMm(pageCount: number, paperType: CoverPaperType = 'white'): number {
  return computeSpineWidthIn(pageCount, paperType) * 25.4
}
